### PR TITLE
fix: fixed error on updatingCompleted

### PR DESCRIPTION
**Pull request by giogaspa**
Hi, this can fix this issue #4 .
I've tested with PostgreSQL and SQLite and it works.

### CODE REVIEW

**Comment by micheleriva** [comment]
Hey @giogaspa thank you for this! I'll ask @faustoq to review the PR.

**Comment by raiindev** [comment]
Hey @giogaspa the PR is perfect! Could you update your branch with the latest changes? (I fixed the GH Workflow that is causing the failing check)

**Review by raiindev — APPROVED** [review]
LGTM

**Comment by giogaspa** [comment]
Hi @raiindev, I've just updated. Thx.

**Pull request merged**
